In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

ruta = "/content/drive/MyDrive/parcial_producciongas/data/raw/produccin-gas-sesco-tight-y-shale-captulo-iv-por-provincia.csv"

df = pd.read_csv(ruta)
df.head()

,anio,mes,indice_tiempo,provincia,concepto,cantidad_mm3
0,2009,1,2009-01,Chubut,Producción convencional,282104.3085
1,2009,1,2009-01,Chubut,Shale gas,0.0000
2,2009,1,2009-01,Chubut,Tight gas,0.0000
3,2009,1,2009-01,Estado Nacional,Producción convencional,141411.1200
4,2009,1,2009-01,Estado Nacional,Shale gas,0.0000

In [ ]:
df.shape

(7494, 6)

In [ ]:
df.columns

Index(['anio', 'mes', 'indice_tiempo', 'provincia', 'concepto',
       'cantidad_mm3'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7494 entries, 0 to 7493
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   anio           7494 non-null   int64
 1   mes            7494 non-null   int64
 2   indice_tiempo  7494 non-null   object
 3   provincia      7494 non-null   object
 4   concepto       7494 non-null   object
 5   cantidad_mm3   7494 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 351.4+ KB

In [ ]:
df.head(10)

,anio,mes,indice_tiempo,provincia,concepto,cantidad_mm3
0,2009,1,2009-01,Chubut,Producción convencional,282104.3085
1,2009,1,2009-01,Chubut,Shale gas,0.0000
2,2009,1,2009-01,Chubut,Tight gas,0.0000
3,2009,1,2009-01,Estado Nacional,Producción convencional,141411.1200
4,2009,1,2009-01,Estado Nacional,Shale gas,0.0000
5,2009,1,2009-01,Estado Nacional,Tight gas,0.0000
6,2009,1,2009-01,Formosa,Producción convencional,3174.0900
7,2009,1,2009-01,Formosa,Shale gas,0.0000
8,2009,1,2009-01,Formosa,Tight gas,0.0000
9,2009,1,2009-01,Jujuy,Producción convencional,425.1600

In [ ]:
df_convencional = df[df["concepto"] == "Producción convencional"].copy()

df_convencional.head()

,anio,mes,indice_tiempo,provincia,concepto,cantidad_mm3
0,2009,1,2009-01,Chubut,Producción convencional,282104.3085
3,2009,1,2009-01,Estado Nacional,Producción convencional,141411.1200
6,2009,1,2009-01,Formosa,Producción convencional,3174.0900
9,2009,1,2009-01,Jujuy,Producción convencional,425.1600
12,2009,1,2009-01,La Pampa,Producción convencional,31245.9560

In [ ]:
df_convencional["provincia"].value_counts()

provincia
Chubut              208
Estado Nacional     208
Formosa             208
Jujuy               208
Mendoza             208
Neuquén             208
Rio Negro           208
Santa Cruz          208
Salta               208
Tierra del Fuego    208
La Pampa            207
San Juan            122
La Rioja             73
Córdoba              15
Misiones              1
Name: count, dtype: int64

In [ ]:
df_tdf = df_convencional[df_convencional["provincia"].str.contains("Tierra", case=False, na=False)].copy()

df_tdf.shape

(208, 6)

In [ ]:
df_tdf.head()

,anio,mes,indice_tiempo,provincia,concepto,cantidad_mm3
33,2009,1,2009-01,Tierra del Fuego,Producción convencional,343023.285
69,2009,2,2009-02,Tierra del Fuego,Producción convencional,316192.464
105,2009,3,2009-03,Tierra del Fuego,Producción convencional,352623.099
141,2009,4,2009-04,Tierra del Fuego,Producción convencional,354955.671
177,2009,5,2009-05,Tierra del Fuego,Producción convencional,363054.169

In [ ]:
df_convencional = df_convencional.sort_values(
    by=["provincia", "anio", "mes"]
).reset_index(drop=True)

df_convencional.head()

   anio  mes indice_tiempo provincia                 concepto  cantidad_mm3
0  2009    1       2009-01    Chubut  Producción convencional   282104.3085
1  2009    2       2009-02    Chubut  Producción convencional   264674.0047
2  2009    3       2009-03    Chubut  Producción convencional   293367.4051
3  2009    4       2009-04    Chubut  Producción convencional   287463.9808
4  2009    5       2009-05    Chubut  Producción convencional   300840.2314

In [ ]:
df_convencional["produccion_mes_anterior"] = df_convencional.groupby("provincia")["cantidad_mm3"].shift(1)

df_convencional["produccion_dos_meses_antes"] = df_convencional.groupby("provincia")["cantidad_mm3"].shift(2)

df_convencional["promedio_3_meses"] = (
    df_convencional
    .groupby("provincia")["cantidad_mm3"]
    .shift(1)
    .rolling(window=3)
    .mean()
)

df_convencional["variacion_mes_anterior"] = (
    df_convencional["cantidad_mm3"] - df_convencional["produccion_mes_anterior"]
)

In [ ]:
df_ml = df_convencional.dropna().copy()

df_ml.shape

(2455, 10)

In [ ]:
df_ml.head()

,anio,mes,indice_tiempo,provincia,concepto,cantidad_mm3,produccion_mes_anterior,produccion_dos_meses_antes,promedio_3_meses,variacion_mes_anterior
3,2009,4,2009-04,Chubut,Producción convencional,287463.9808,293367.4051,264674.0047,280048.572767,-5903.4243
4,2009,5,2009-05,Chubut,Producción convencional,300840.2314,287463.9808,293367.4051,281835.130200,13376.2506
5,2009,6,2009-06,Chubut,Producción convencional,294138.6128,300840.2314,287463.9808,293890.539100,-6701.6186
6,2009,7,2009-07,Chubut,Producción convencional,304828.4822,294138.6128,300840.2314,294147.608333,10689.8694
7,2009,8,2009-08,Chubut,Producción convencional,305871.6603,304828.4822,294138.6128,299935.775467,1043.1781

In [ ]:
df_ml.columns

Index(['anio', 'mes', 'indice_tiempo', 'provincia', 'concepto', 'cantidad_mm3',
       'produccion_mes_anterior', 'produccion_dos_meses_antes',
       'promedio_3_meses', 'variacion_mes_anterior'],
      dtype='object')

In [ ]:
df["concepto"].unique()
df_convencional.shape
df_tdf.shape
df_ml.shape

(2455, 10)

In [ ]:
df_convencional = df[df["concepto"] == "Producción convencional"].copy()

df_convencional = df_convencional.sort_values(
    by=["provincia", "anio", "mes"]
).reset_index(drop=True)

df_convencional["produccion_mes_anterior"] = (
    df_convencional.groupby("provincia")["cantidad_mm3"].shift(1)
)

df_convencional["produccion_dos_meses_antes"] = (
    df_convencional.groupby("provincia")["cantidad_mm3"].shift(2)
)

df_convencional["promedio_3_meses"] = (
    df_convencional.groupby("provincia")["cantidad_mm3"]
    .transform(lambda x: x.shift(1).rolling(window=3).mean())
)

df_convencional["variacion_mes_anterior"] = (
    df_convencional["produccion_mes_anterior"] -
    df_convencional["produccion_dos_meses_antes"]
)

df_ml = df_convencional.dropna().copy()

df_ml.shape

(2455, 10)

In [ ]:
df_ml.head()

,anio,mes,indice_tiempo,provincia,concepto,cantidad_mm3,produccion_mes_anterior,produccion_dos_meses_antes,promedio_3_meses,variacion_mes_anterior
3,2009,4,2009-04,Chubut,Producción convencional,287463.9808,293367.4051,264674.0047,280048.572767,28693.4004
4,2009,5,2009-05,Chubut,Producción convencional,300840.2314,287463.9808,293367.4051,281835.130200,-5903.4243
5,2009,6,2009-06,Chubut,Producción convencional,294138.6128,300840.2314,287463.9808,293890.539100,13376.2506
6,2009,7,2009-07,Chubut,Producción convencional,304828.4822,294138.6128,300840.2314,294147.608333,-6701.6186
7,2009,8,2009-08,Chubut,Producción convencional,305871.6603,304828.4822,294138.6128,299935.775467,10689.8694

In [ ]:
df_ml.columns

Index(['anio', 'mes', 'indice_tiempo', 'provincia', 'concepto', 'cantidad_mm3',
       'produccion_mes_anterior', 'produccion_dos_meses_antes',
       'promedio_3_meses', 'variacion_mes_anterior'],
      dtype='object')

In [ ]:
df_ml["provincia"].value_counts()

provincia
Chubut              205
Estado Nacional     205
Jujuy               205
Formosa             205
Neuquén             205
Mendoza             205
Tierra del Fuego    205
Santa Cruz          205
Rio Negro           205
Salta               205
La Pampa            204
San Juan            119
La Rioja             70
Córdoba              12
Name: count, dtype: int64

In [ ]:
df_ml[df_ml["provincia"].str.contains("Tierra", case=False, na=False)].shape

(205, 10)

In [ ]:
df_ml.shape

(2455, 10)

In [ ]:
df["provincia"].unique()

array(['Chubut', 'Estado Nacional', 'Formosa', 'Jujuy', 'La Pampa',
       'Mendoza', 'Neuquén', 'Rio Negro', 'Salta', 'San Juan',
       'Santa Cruz', 'Tierra del Fuego', 'Misiones', 'La Rioja',
       'Córdoba'], dtype=object)

In [ ]:
provincias_patagonicas = [
    "Tierra del Fuego",
    "Santa Cruz",
    "Chubut",
    "Río Negro",
    "Neuquén"
]

df_patagonia = df[
    (df["concepto"] == "Producción convencional") &
    (df["provincia"].isin(provincias_patagonicas))
].copy()

df_patagonia.shape

(832, 6)

In [ ]:
df_convencional = df_patagonia.copy()

Nuevo enfoque del proyecto

A partir de la revisión del dataset, se ajusta el trabajo para usar provincias patagónicas productoras de gas convencional. Tierra del Fuego se mantiene como caso principal de análisis, pero se incorporan otras provincias para contar con más registros para el modelo.

In [ ]:
# Revisamos nuevamente las provincias disponibles en el dataset

df["provincia"].unique()

array(['Chubut', 'Estado Nacional', 'Formosa', 'Jujuy', 'La Pampa',
       'Mendoza', 'Neuquén', 'Rio Negro', 'Salta', 'San Juan',
       'Santa Cruz', 'Tierra del Fuego', 'Misiones', 'La Rioja',
       'Córdoba'], dtype=object)

In [ ]:
# Recorte territorial del proyecto
# Seleccionamos provincias patagónicas productoras de gas convencional

provincias_patagonicas = [
    "Tierra del Fuego",
    "Santa Cruz",
    "Chubut",
    "Rio Negro",
    "Neuquén"
]

df_patagonia = df[
    (df["concepto"] == "Producción convencional") &
    (df["provincia"].isin(provincias_patagonicas))
].copy()

df_patagonia.shape

(1040, 6)

In [ ]:
# Ordenamos los datos por provincia, año y mes

df_patagonia = df_patagonia.sort_values(
    by=["provincia", "anio", "mes"]
).reset_index(drop=True)

df_patagonia.head()

   anio  mes indice_tiempo provincia                 concepto  cantidad_mm3
0  2009    1       2009-01    Chubut  Producción convencional   282104.3085
1  2009    2       2009-02    Chubut  Producción convencional   264674.0047
2  2009    3       2009-03    Chubut  Producción convencional   293367.4051
3  2009    4       2009-04    Chubut  Producción convencional   287463.9808
4  2009    5       2009-05    Chubut  Producción convencional   300840.2314

In [ ]:
# Creamos variables históricas para adaptar el dataset a Machine Learning

df_patagonia["produccion_mes_anterior"] = (
    df_patagonia.groupby("provincia")["cantidad_mm3"].shift(1)
)

df_patagonia["produccion_dos_meses_antes"] = (
    df_patagonia.groupby("provincia")["cantidad_mm3"].shift(2)
)

df_patagonia["promedio_3_meses"] = (
    df_patagonia.groupby("provincia")["cantidad_mm3"]
    .transform(lambda x: x.shift(1).rolling(window=3).mean())
)

df_patagonia["variacion_mes_anterior"] = (
    df_patagonia["produccion_mes_anterior"] -
    df_patagonia["produccion_dos_meses_antes"]
)

df_ml = df_patagonia.dropna().copy()

df_ml.shape

(1025, 10)

In [ ]:
df_ml.head()

,anio,mes,indice_tiempo,provincia,concepto,cantidad_mm3,produccion_mes_anterior,produccion_dos_meses_antes,promedio_3_meses,variacion_mes_anterior
3,2009,4,2009-04,Chubut,Producción convencional,287463.9808,293367.4051,264674.0047,280048.572767,28693.4004
4,2009,5,2009-05,Chubut,Producción convencional,300840.2314,287463.9808,293367.4051,281835.130200,-5903.4243
5,2009,6,2009-06,Chubut,Producción convencional,294138.6128,300840.2314,287463.9808,293890.539100,13376.2506
6,2009,7,2009-07,Chubut,Producción convencional,304828.4822,294138.6128,300840.2314,294147.608333,-6701.6186
7,2009,8,2009-08,Chubut,Producción convencional,305871.6603,304828.4822,294138.6128,299935.775467,10689.8694

In [ ]:
df_ml["provincia"].value_counts()

provincia
Chubut              205
Neuquén             205
Rio Negro           205
Santa Cruz          205
Tierra del Fuego    205
Name: count, dtype: int64

In [ ]:
df_patagonia.shape

(1040, 10)

In [ ]:
df_ml.shape

(1025, 10)

In [ ]:
df_ml["provincia"].value_counts()

provincia
Chubut              205
Neuquén             205
Rio Negro           205
Santa Cruz          205
Tierra del Fuego    205
Name: count, dtype: int64

In [ ]:
ruta_salida = "/content/drive/MyDrive/parcial_producciongas/data/processed/produccin-gas-sesco-tight-y-shale-captulo-iv-por-provincia.csv"

df_ml.to_csv(ruta_salida, index=False)

ruta_salida

'/content/drive/MyDrive/parcial_producciongas/data/processed/produccin-gas-sesco-tight-y-shale-captulo-iv-por-provincia.csv'

In [ ]:
import os

os.path.exists(ruta_salida)

True

In [4]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [5]:
%cd /content/drive/MyDrive/parcial_producciongas

/content/drive/MyDrive/parcial_producciongas

In [6]:
!git init
!git config user.name "Gonzalo Ortiz"
!git config user.email "ortizcarlosgonzalo@gmail.com"

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/drive/MyDrive/parcial_producciongas/.git/

In [7]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data/
	notebooks/
	reports/

nothing added to commit but untracked files present (use "git add" to track)

In [8]:
!git add data notebooks reports

In [9]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   data/processed/produccin-gas-sesco-tight-y-shale-captulo-iv-por-provincia.csv
	new file:   data/raw/produccin-gas-sesco-tight-y-shale-captulo-iv-por-provincia.csv
	new file:   notebooks/parcial_producciongas.ipynb
	new file:   "reports/Aprendizaje automa\314\201tico_entrega2_GonzaloOrtiz.pdf"
	new file:   "reports/ENTREGA1_EVALUACIO\314\201N PARCIAL_ APRENDIZAJE AUTOMA\314\201TICO_GonzaloOrtiz.pdf"

In [10]:
!git commit -m "Entrega 2 dataset y origen"

[master (root-commit) 6db62e1] Entrega 2 dataset y origen
 5 files changed, 8522 insertions(+)
 create mode 100644 data/processed/produccin-gas-sesco-tight-y-shale-captulo-iv-por-provincia.csv
 create mode 100644 data/raw/produccin-gas-sesco-tight-y-shale-captulo-iv-por-provincia.csv
 create mode 100644 notebooks/parcial_producciongas.ipynb
 create mode 100644 "reports/Aprendizaje automa\314\201tico_entrega2_GonzaloOrtiz.pdf"
 create mode 100644 "reports/ENTREGA1_EVALUACIO\314\201N PARCIAL_ APRENDIZAJE AUTOMA\314\201TICO_GonzaloOrtiz.pdf"

In [11]:
!git branch -M main

In [12]:
!git remote add origin https://github.com/GonzaOrtiz85/parcial_producciongas.git

In [13]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [14]:
!git status

On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   notebooks/parcial_producciongas.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [2]:
%cd /content/drive/MyDrive/parcial_producciongas
!git status

/content/drive/MyDrive/parcial_producciongas
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   notebooks/parcial_producciongas.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [5]:
from getpass import getpass

token = getpass("Pegá tu token de GitHub")
usuario = "GonzaOrtiz85"
repo = "parcial_producciongas"

!git remote set-url origin https://{usuario}:{token}@github.com/{usuario}/{repo}.git
!git push -u origin main

Pegá tu token de GitHub··········
To https://github.com/GonzaOrtiz85/parcial_producciongas.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/GonzaOrtiz85/parcial_producciongas.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

In [6]:
!git push -u origin main --force

Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 2 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 3.15 MiB | 3.85 MiB/s, done.
Total 12 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), done.
To https://github.com/GonzaOrtiz85/parcial_producciongas.git
 + ac273f5...6db62e1 main -> main (forced update)
Branch 'main' set up to track remote branch 'main' from 'origin'.

In [7]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).